stages:
  - test
  - build_base_image


run tests:
  stage: test
  image: qboson-docker-registry-vpc.cn-beijing.cr.aliyuncs.com/kaiwuapp/kaiwu-pytorch-plugin-runtime:py3.10
  tags:
    - kaiwu_dev
  script:
    - export PYTHONPATH=$CI_PROJECT_DIR
    - echo "==============Start all tests=========="
    - make all_tests
    - echo "==============End all test=========="

build_base_image:
  stage: build_base_image
  tags:
    - shell-runner1
  script:
    - docker build -t kaiwu-pytorch-plugin-runtime:py3.10 .
    - docker tag kaiwu-pytorch-plugin-runtime:py3.10 qboson-docker-registry-vpc.cn-beijing.cr.aliyuncs.com/kaiwuapp/kaiwu-pytorch-plugin-runtime:py3.10
    - docker login --username=$CI_DOCKER_USERNAME --password=$CI_DOCKER_PASSWORD qboson-docker-registry-vpc.cn-beijing.cr.aliyuncs.com
    - docker push qboson-docker-registry-vpc.cn-beijing.cr.aliyuncs.com/kaiwuapp/kaiwu-pytorch-plugin-runtime:py3.10
  when: manual
